version: '3.4'
services:

  postgres:
    image: postgres:14-alpine
    ports:
    - 5432:5432
    env_file: env/postgres.env
    volumes:
    - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
